### PR TITLE
Add icons for FindReplaceOverlay

### PR DESCRIPTION
**Pull request by Wittmaxi**
grafik
grafik

Add the images used in the editor overlay used to perform find/replace. The images are only added in svg-format whereas they are used in png-format in the Overlay.

In particular, a few new images were created and/or adapted from www.iconbolt.com.

This PR acommodates
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192

### CODE REVIEW

**Review by HeikoKlare — COMMENTED** [review]
@Wittmaxi I think the `close_replace` and `open_replace` icons can now be removed as they have been replaced with font icons, can't they?

Once we have an agreement on the folders to place the icons in (see https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192#issuecomment-2137787136), that should also be reflected in this PR.

**Review by HeikoKlare — APPROVED** [review]
Should be merged along with eclipse-platform/eclipse.platform.ui#1192.

**Comment by akurtakov** [comment]
Is this one still needed?

**Comment by Wittmaxi** [comment]
@akurtakov I believe so, somehow it was never merged!

**Comment by akurtakov** [comment]
@HeikoKlare would you please review/merge this one?

**Comment by akurtakov** [comment]
@BeckerWdf As our images guy maybe you can verify everything is good here?

**Review by BeckerWdf — CHANGES_REQUESTED** [review]
- Images have been moved to elcl folder. Pls. adapt this change accordingsly
- Pls also add the *.png and the *@2x.png in the eclipse-png folder

**Comment by Wittmaxi** [comment]
@BeckerWdf does https://github.com/eclipse-platform/eclipse.platform.images/commit/48c2ab573d2183cb2cf2338fca8ad445b85abc44 address your comment correctly?

**Review by BeckerWdf — APPROVED** [review]

**Comment by HeikoKlare** [comment]
Thank you for checking and merging this, @BeckerWdf!

**Pull request merged**
