### PR TITLE
fix icon position accordingly to UI Guidelines

### PR DESCRIPTION
**Pull request by Michael5601**
This PR fixes some SVGs and PNGs positioning for two unique icons. The offset to the left and right is now one pixel. 

I also fixed all duplicates I could find. 
The disabled icons also need to be changed but I never generated them with the Image-Renderer. @BeckerWdf maybe you could do this?

Do we need to change the PNGs in Eclipse or are they interconnected to this repo?

### CODE REVIEW

**Comment by vogella** [comment]
Awesome, thanks you.

Could you also provide PR for the eclipse.platform and eclipse.platform.ui repos to use these new icons so that we can test the change?

**Comment by Michael5601** [comment]
> Awesome, thanks you.
> 
> Could you also provide PR for the eclipse.platform and eclipse.platform.ui repos to use these new icons so that we can test the change?

It would be great if someone else can do this as I have problems with our company firewall and the Eclipse installer. I can't get a new configuration for this change right now. Alternatively I will provide it as soon as my problems are fixed.

**Comment by merks** [comment]
@Michael5601 

I wonder, are you using the latest installer?   These should work better using (on Windows) because they use system certificate store.

https://www.eclipse.org/downloads/packages/release/2024-12/rc1

**Comment by Michael5601** [comment]
> @Michael5601
> 
> I wonder, are you using the latest installer? These should work better using (on Windows) because they use system certificate store.
> 
> https://www.eclipse.org/downloads/packages/release/2024-12/rc1

Yes I used the latest, this is not an issue of Eclipse. Some people had similar issues here. But I will fix it soon

**Comment by Michael5601** [comment]
> Ideally the shapes should always start at exact pixel locations. See here: image
> 
> The circle does not start at exactly 1,1 The triangle does not start exactly 6,3 and hight should be 10 and width should also be 6 or 7 but not something between.
> 
> > The disabled icons also need to be changed but I never generated them with the Image-Renderer. @BeckerWdf maybe you could do this?
> 
> Sorry I won't find time next days. You can do it.
> 
> > Do we need to change the PNGs in Eclipse or are they interconnected to this repo?
> 
> Yes you have to copy them over manually.

I will fix it.

**Comment by Michael5601** [comment]
I created the disabled icons and changed the PNGs in the bundles. I don't know if there are any more places where the icons need to be changed. I tried to find them with the search tool and via their location in the images repository. There were 18 icons in platform and 2 in jdt.ui

**Comment by BeckerWdf** [comment]
> Thanks @Michael5601 I assume https://github.com/eclipse-pde/eclipse.pde/ would also need an update, as they also use for example the run icon. Can you check?

I scroll through the "etool16" / "elcl16" forders of the org.eclipse.pde.* bundles. I did not see the run icon there.

**Comment by Michael5601** [comment]
> > I will fix it.
> 
> Thanks a lot.

I think we can merge right? Everything must be done now. :)

**Pull request merged**
