### PR TITLE
Improve Onboarding Icon for Java Perspectives

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Matthias, I honestly dislike both versions (with/without "hook") and even think the "hook" looks even more strange.
Ideally we could simply remove this line - this would be improvement from my point of view.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
Can we please just remove the line in question?

**Comment by vogella** [comment]
Old icons reminds we of a "Kochtopf". +1 for removing them. Would also be nice if they would be removed in the original icon.

**Comment by BeckerWdf** [comment]
Ok. I removed the line

**Review by iloveeclipse — APPROVED** [review]
Thanks. I really appreciate your effort / craftsmanship.

**Comment by BeckerWdf** [comment]
> Thanks. I really appreciate your effort / craftsmanship.

Thanks for *your* effort / feedback

**Pull request merged**
