### PR TITLE
Adjustment to SVG icons for JSVG integration

### PR DESCRIPTION
**Pull request by Michael5601**
This PR fixes all icons described in https://github.com/eclipse-platform/eclipse.platform.images/issues/104.
Most icons could be fixed without changing their looks. JSVG most of the time did a better job displaying details of the icon, if compared to the reference PNG. So these fixes are rather general fixes than special fixes for JSVG.

### CODE REVIEW

**Comment by BeckerWdf** [comment]
I compare the SVGs in the GitHub compare UI. I didn't see any difference.
Can you please elaborate a bit more on the changes you made?

Will you also create PRs to update the PNGs in the actual "productive" bundles?

**Comment by Michael5601** [comment]
> I compare the SVGs in the GitHub compare UI. I didn't see any difference. Can you please elaborate a bit more on the changes you made?
> 
> Will you also create PRs to update the PNGs in the actual "productive" bundles?

I will describe the changes for each section from https://github.com/eclipse-platform/eclipse.platform.images/issues/104:

**Surrounding white filter:**
I just deleted the white filter around some of the items. In my opinion it is badly done and unnecessary. You can't see these changes because this white filter is not rendered by most renderers. JSVG had them rendered so they looked a little bit off even though they were closer to the original. 

**Unwanted white space:**
This is the same problem as **Surrounding white filter** but JSVG rendered this filter as white space and not as filter (blurred white). In the PNGs the filter was just ignored so they look different than the SVGs. I also just deleted this filter.

**Unwanted colored area:**
This colored area was caused by a short path in this area. The path had no impact rather than confusing JSVG, which is why it was ratserized colorful. I deleted the path. 

**Filter around numbers:**
Again similar to **Surrounding white filter** but only around numbers. The filter could only be seen in the rasterized images of JSVG and not in the PNGs. Here again JSVG was closer to the original. I deleted the filter. 

**Full icon wrong color:**
There were plenty of layers that had no impact. As soon as I deleted these layers, JSVG rendered the icon in the same color as the PNG. Again you see no difference as the layers were probably just ignored by other renderers. It can be argued that this is a mistake from JSVG as it didn't ignore the layers. 

**Bad text presentation:**
The text was not converted to paths so the rasterized text looks different in every rasterizer result. I converted the text to paths as already done in my previous PR that you reviewed. 

**Empty image:**
This image is weird because it was created in Adobe Illustrator and consisted of a SVG`<switch/>` element. As I learned a switch element evaluates any `requiredExtension` property and renders the first child were these attributes are true. This switch only had one child that would draw the whole image. An Adobe URL was set in the `requiredExtension` property. In Inkscape it wasn't possible to change the icon because there was only this one child/path that drew the whole image. I simplified the SVG by deleting the `switch` and the `requiredExtension`-property so the path is drawn directly. After this the size of the icon was way to large when I opened it in Inkscape, so I changed the size in Inkscape to resemble the original size. 

I hope this could give you some insights. In my opinion changing the PNGs is not necessary because my change just made the SVGs more aligned to the PNGs looks. The only changes that could make a very small difference are the changes to the filters but as you see in the Github UI it does not seem like there is a difference. 

I also want to note that the icons are in very bad shape. I am not a pro in design but I study "Medieninformatik"(media computer science) which has a small design part to it and many problems in the icons come mostly from beginner mistakes:

- The icons have many gradients that make them look very old school.
- The SVGs have many unnecessary layers that sometimes are not even in the view area. This is just garbage that should be deleted before deploying the icons to the customer. In the worst case they distort the image that is generated by rasterizers like JSVG. 
- The icons are very detailed. For example the yellow trail in `new.svg` (part of this PR) consists of little yellow stars with yellow filter around them. It's impossible to see details like this in a resolution of 32x32px or even smaller.
- Sometimes the icons are not placed centered to the view area in the SVGs. This means that on the left there is a 1px white space and the right side is cut a bit.

**Comment by akurtakov** [comment]
Thanks for that it was very informative for me!

**Comment by BeckerWdf** [comment]
> I also want to note that the icons are in very bad shape. I am not a pro 

Me neither. I just did my best.
The SVGs where created "after the fact". Initially we only had GIFs in 16x16 px. Then we started to re-created SVGs so be able to render PNGs in 16x16 px but also in 32x32 px. 

> many problems in the icons come mostly from beginner mistakes:
> 
> * The icons have many gradients that make them look very old school.

During the process of re-creating the icons as SVGs it was not the task to make the icons look modern but just replicate what was already there. And I agree that this looks "old school" nowadays".

> * The SVGs have many unnecessary layers that sometimes are not even in the view area. This is just garbage that should be deleted before deploying the icons to the customer. In the worst case they distort the image that is generated by rasterizers like JSVG.

If you have specific examples. We might able to improve on that.

> * The icons are very detailed. For example the yellow trail in `new.svg` (part of this PR) consists of little yellow stars with yellow filter around them. It's impossible to see details like this in a resolution of 32x32px or even smaller.

We can improve on that.

> * Sometimes the icons are not placed centered to the view area in the SVGs. This means that on the left there is a 1px white space and the right side is cut a bit.

The Eclipse UI Guideline as a [big section](https://eclipse-platform.github.io/ui-best-practices/#ui-graphics) about icon design. And there these 1px padding is described. So this is rather correct.

**Comment by Michael5601** [comment]
> > I also want to note that the icons are in very bad shape. I am not a pro
> 
> Me neither. I just did my best. The SVGs where created "after the fact". Initially we only had GIFs in 16x16 px. Then we started to re-created SVGs so be able to render PNGs in 16x16 px but also in 32x32 px.
> 
> > many problems in the icons come mostly from beginner mistakes:
> > 
> > * The icons have many gradients that make them look very old school.
> 
> During the process of re-creating the icons as SVGs it was not the task to make the icons look modern but just replicate what was already there. And I agree that this looks "old school" nowadays".
> 
> > * The SVGs have many unnecessary layers that sometimes are not even in the view area. This is just garbage that should be deleted before deploying the icons to the customer. In the worst case they distort the image that is generated by rasterizers like JSVG.
> 
> If you have specific examples. We might able to improve on that.
> 
> > * The icons are very detailed. For example the yellow trail in `new.svg` (part of this PR) consists of little yellow stars with yellow filter around them. It's impossible to see details like this in a resolution of 32x32px or even smaller.
> 
> We can improve on that.
> 
> > * Sometimes the icons are not placed centered to the view area in the SVGs. This means that on the left there is a 1px white space and the right side is cut a bit.
> 
> The Eclipse UI Guideline as a [big section](https://eclipse-platform.github.io/ui-best-practices/#ui-graphics) about icon design. And there these 1px padding is [described](https://eclipse-platform.github.io/ui-best-practices/#icon_size_placement). So this is rather correct.

I appreciate your effort in the creation of the SVGs as they enable the project that I work on right now. I think is is a very big task to improve all icons. When a rasterization library is integrated in Eclipse we will see some icons that are in a bad shape. A big step in the looks of Eclipse can be done by fixing these icons rather than fixing all icons as most are rendered correctly. As the integration of vector graphics in Eclipse makes most raster graphics redundant we can also achieve better looks for Eclipse and don't rely on fixing the PNGs.

**Comment by BeckerWdf** [comment]
So the change are ok for me. Should I merge this PR?

**Pull request merged**
