### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
I have created this with the GitHub Tools. What do you think?

**Review by iloveeclipse — APPROVED** [review]
LGTM

**Comment by akurtakov** [comment]
Do you plan fixing the license headers?

**Comment by BeckerWdf** [comment]
Sure I can.
Do we need them at all when we have the licence file?

**Comment by akurtakov** [comment]
It's good practice that every file has the license header - this makes it clear when code gets copied around and etc.

**Comment by BeckerWdf** [comment]
Done. See https://github.com/eclipse-platform/eclipse.platform.images/pull/3

**Pull request merged**
