### PR TITLE
Change File Header to EPL 2

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by akurtakov** [comment]
```
git grep v1.0
```
gives me few more instances of EPL 1.0

**Comment by BeckerWdf** [comment]
> ```
> git grep v1.0
> ```
> 
> gives me few more instances of EPL 1.0

should be fixed now.

**Comment by BeckerWdf** [comment]
@akurtakov: Can you pls. approve?

**Review by iloveeclipse — APPROVED** [review]
LGTM

**Pull request merged**
